name: example
description: Example project on how to use liqpay
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Utility
  uuid: ^4.5.1
  intl: ^0.20.2

  # UI
  flutter_credit_card: ^4.1.0

  webview_flutter: ^4.13.0

  liqpay:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.olegnovosad.liqpay.example
    iosBundleIdentifier: com.olegnovosad.liqpay.example
